import type { InsertRegion, InsertCostProfile } from "@shared/schema";

// ---------------------------------------------------------------------------
// Verified regional data, transcribed from the research report
// "Potato (Solanum tuberosum) Gross Margin & Cost-of-Production Data — 14
// Australian Growing Regions" (prepared 9 Aug 2026). Every figure below
// carries the exact source and year it was published under in that report.
// ---------------------------------------------------------------------------

export const REGIONS: InsertRegion[] = [
  { id: "tas-north", name: "Tasmania — Northern / North-West", state: "Tasmania", sortOrder: 1, dataQuality: "regional", productionShare: ">90% of Tasmanian production", summary: "The single best public dataset in Australia for potato economics: itemised Nov 2020 budgets across fresh, processing and seed." },
  { id: "tas-south", name: "Tasmania — Southern / Midlands", state: "Tasmania", sortOrder: 2, dataQuality: "regional", productionShare: "<10% of Tasmanian production", summary: "Itemised Nov 2020 Low Rainfall budget models the Midlands district." },
  { id: "vic-central", name: "Victoria — Ballarat / Central", state: "Victoria", sortOrder: 3, dataQuality: "none", productionShare: "Part of Victoria's 7,587 ha / 292 kt / $137m (2013-14)", summary: "No region-specific potato economics exist in the public domain. Victoria's own water-economics study excluded potatoes from its gross margin table entirely." },
  { id: "vic-gippsland", name: "Victoria — Gippsland / Thorpdale", state: "Victoria", sortOrder: 4, dataQuality: "none", productionShare: "Victoria's most potato-intensive region by area share", summary: "No yield, price or cost data of any kind. Thorpdale is a certified seed district; West Gippsland is Victoria's #1 potato catchment." },
  { id: "vic-mallee", name: "Victoria — Mallee", state: "Victoria", sortOrder: 5, dataQuality: "none", productionShare: "5.97% of Mallee/Wimmera vegetable area", summary: "No yield, price or cost data of any kind." },
  { id: "sa-adelaide", name: "South Australia — Northern Adelaide Plains (Virginia)", state: "South Australia", sortOrder: 6, dataQuality: "state_proxy", productionShare: "22.5% of Adelaide Plains gross ag. value", summary: "Region-specific yield and water use exist; costs are only available as a 2005 state aggregate." },
  { id: "sa-riverland", name: "South Australia — Riverland / Mallee", state: "South Australia", sortOrder: 7, dataQuality: "state_proxy", productionShare: "15% of national production", summary: "Region-specific yield and water use exist; costs are only available as a 2005 state aggregate." },
  { id: "sa-limestone", name: "South Australia — Limestone Coast (South East)", state: "South Australia", sortOrder: 8, dataQuality: "state_proxy", productionShare: "10% of national production", summary: "Region-specific yield and water use exist; costs are only available as a 2005 state aggregate." },
  { id: "nsw-riverina", name: "NSW — Riverina", state: "New South Wales", sortOrder: 9, dataQuality: "regional", productionShare: "70% of NSW production", summary: "Three fully itemised 2013 NSW DPI budgets (2012 prices) — the second-best public dataset in Australia." },
  { id: "nsw-tablelands", name: "NSW — Central / Southern Tablelands", state: "New South Wales", sortOrder: 10, dataQuality: "none", productionShare: "20% of NSW production", summary: "No separate budget was ever published. Publisher states Tablelands yields run ~20% above Riverina — an approximation, not an observation." },
  { id: "wa-manjimup", name: "Western Australia — Manjimup / Pemberton", state: "Western Australia", sortOrder: 11, dataQuality: "state_proxy", productionShare: "36% of Preston-Warren-Blackwood vegetable area", summary: "District-specific water use is directly measured; yield and gross margin are 2005-2013 state-level estimates." },
  { id: "wa-perth", name: "Western Australia — Perth / Myalup", state: "Western Australia", sortOrder: 12, dataQuality: "state_proxy", productionShare: "33% of Peel-Harvey vegetable area", summary: "District-specific water use is directly measured; a 2013 modelled gross margin exists for Medina/Dandaragan." },
  { id: "qld-atherton", name: "Queensland — Atherton Tablelands", state: "Queensland", sortOrder: 13, dataQuality: "regional", productionShare: "60-67% of Far North Qld vegetable area/value", summary: "One of the only region-labelled gross margins outside Tas/NSW — but it dates from 1998." },
  { id: "qld-lockyer", name: "Queensland — Lockyer Valley", state: "Queensland", sortOrder: 14, dataQuality: "regional", productionShare: "13% of Lockyer-Fassifern vegetable area", summary: "Region-labelled 1998 gross margin; too old for current decisions." },
];

export const COST_PROFILES: InsertCostProfile[] = [
  // ---------------------------------------------------------------- Tas North
  {
    regionId: "tas-north", segment: "fresh", segmentLabel: "Fresh / Table",
    yieldTHa: 45, priceT: 550,
    grossIncomeHa: 17550,
    seedCostHa: 1950, fertiliserCostHa: 1374.75, cropProtectionCostHa: 481.83,
    irrigationCostHa: 297.5, waterUseMlHa: 3.5,
    machineryCostHa: 144.75, contractCostHa: 1437.5 + 2362.5,
    labourCostHa: 1899.75, labourRateHr: 30,
    postHarvestCostHa: null, overheadPct: 2,
    totalVariableCostHa: 10300, grossMarginHa: 7250,
    dataQuality: "regional", sourceName: "NRE Tasmania Crop Gross Margins — High Rainfall",
    sourceUrl: "https://nre.tas.gov.au/Documents/Crop%20GMs_High%20Rainfall.xlsx", sourceYear: "2020",
    notes: "Meander Valley High Rainfall budget, proxy for Northern/NW district which carries >90% of Tas production. Two-tier pricing (27t premium @ $550/t + 9t second-grade @ $300/t on the 45 t/ha crop) makes gross income ($17,550/ha) a published figure, not yield x price — priceT shown is the premium-grade rate only.",
  },
  {
    regionId: "tas-north", segment: "processing", segmentLabel: "Processing — French Fries",
    yieldTHa: 55.775, priceT: 330,
    grossIncomeHa: 18410,
    seedCostHa: 1512.5, fertiliserCostHa: 1834.63, cropProtectionCostHa: 631.6,
    irrigationCostHa: 315, waterUseMlHa: 5.25,
    machineryCostHa: 75.75, contractCostHa: 1295 + 3018.75,
    labourCostHa: 30.75, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: 2,
    totalVariableCostHa: 9090, grossMarginHa: 9320,
    dataQuality: "regional", sourceName: "NRE Tasmania Crop Gross Margins — High Rainfall",
    sourceUrl: "https://nre.tas.gov.au/Documents/Crop%20GMs_High%20Rainfall.xlsx", sourceYear: "2020",
    notes: "Russet Burbank, High Rainfall zone. Yield shown is paid yield (55.775 t/ha of a 57.5 t/ha gross crop); gross income ($18,410/ha) is the published figure.",
  },
  {
    regionId: "tas-north", segment: "seed", segmentLabel: "Seed Potatoes",
    yieldTHa: 39.96, priceT: 507,
    grossIncomeHa: 20260,
    seedCostHa: 2100, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 3.5,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: 9150, grossMarginHa: 11110,
    dataQuality: "regional", sourceName: "NRE Tasmania Crop Gross Margins — High Rainfall",
    sourceUrl: "https://nre.tas.gov.au/Documents/Crop%20GMs_High%20Rainfall.xlsx", sourceYear: "2020",
    notes: "High Rainfall zone seed budget; only seed cost and totals itemised in source. Gross income ($20,260/ha) and total variable cost ($9,150/ha) are both published, so the itemised gap doesn't affect the baseline margin.",
  },
  // ---------------------------------------------------------------- Tas South
  {
    regionId: "tas-south", segment: "fresh", segmentLabel: "Fresh / Table",
    yieldTHa: 40, priceT: 550,
    grossIncomeHa: 15600,
    seedCostHa: 1950, fertiliserCostHa: 1374.84, cropProtectionCostHa: 513.05,
    irrigationCostHa: 157.5, waterUseMlHa: 3.5,
    machineryCostHa: 55.5, contractCostHa: 1185.5 + 2100,
    labourCostHa: 1610.5, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: 2,
    totalVariableCostHa: 9260, grossMarginHa: 6340,
    dataQuality: "regional", sourceName: "NRE Tasmania Crop Gross Margins — Low Rainfall",
    sourceUrl: "https://nre.tas.gov.au/Documents/Crop%20GMs_Low%20Rainfall.xlsx", sourceYear: "2020",
    notes: "Low Rainfall / Midlands budget; Southern division is <10% of Tas production. Two-tier pricing (24t premium @ $550/t + 8t second-grade @ $300/t on the 40 t/ha crop) — gross income ($15,600/ha) is the published figure, not yield x price.",
  },
  {
    regionId: "tas-south", segment: "processing", segmentLabel: "Processing — French Fries",
    yieldTHa: 52.25, priceT: 330,
    grossIncomeHa: 17250,
    seedCostHa: 1512.5, fertiliserCostHa: 1834.76, cropProtectionCostHa: null,
    irrigationCostHa: 238.5, waterUseMlHa: 5.3,
    machineryCostHa: null, contractCostHa: 1925 + 990,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: 2,
    totalVariableCostHa: 8940, grossMarginHa: 8310,
    dataQuality: "regional", sourceName: "NRE Tasmania Crop Gross Margins — Low Rainfall",
    sourceUrl: "https://nre.tas.gov.au/Documents/Crop%20GMs_Low%20Rainfall.xlsx", sourceYear: "2020",
    notes: "Yield shown is paid yield (52.25 t/ha of a 55 t/ha gross crop); gross income ($17,250/ha) is the published figure.",
  },
  {
    regionId: "tas-south", segment: "seed", segmentLabel: "Seed Potatoes",
    yieldTHa: 37.74, priceT: 507,
    grossIncomeHa: 19140,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: null,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: 9340, grossMarginHa: 9800,
    dataQuality: "regional", sourceName: "NRE Tasmania Crop Gross Margins — Low Rainfall",
    sourceUrl: "https://nre.tas.gov.au/Documents/Crop%20GMs_Low%20Rainfall.xlsx", sourceYear: "2020",
    notes: "Only paid yield, price and totals itemised for the seed segment in this budget. Gross income ($19,140/ha) and total variable cost ($9,340/ha) are both published.",
  },
  // ---------------------------------------------------------------- Vic Central (no data)
  {
    regionId: "vic-central", segment: "unspecified", segmentLabel: "All segments",
    yieldTHa: 38.5, priceT: 251,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 5,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: null, grossMarginHa: null,
    dataQuality: "none", sourceName: "Victorian Potato Industry Strategic Plan 2015/16-2019/20 (yield); AUSVEG Discussion Paper, ABARES 2008-09 (price)",
    sourceUrl: "https://www.auspica.org.au/wp-content/uploads/2018/02/Strategic-Plan-Victorian-Potato-Industry-Final.pdf", sourceYear: "2015 / c.2011",
    notes: "Victoria's own gross margin study excluded potatoes entirely. Yield and price shown are state averages, not regional figures — no cost data exists at any level for this region. A grower survey is the only realistic path to real numbers here.",
  },
  // ---------------------------------------------------------------- Vic Gippsland (no data)
  {
    regionId: "vic-gippsland", segment: "unspecified", segmentLabel: "All segments",
    yieldTHa: 38.5, priceT: 251,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 5,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: null, grossMarginHa: null,
    dataQuality: "none", sourceName: "Victorian Potato Industry Strategic Plan (yield); AUSVEG Discussion Paper, ABARES 2008-09 (price)",
    sourceUrl: "https://www.auspica.org.au/wp-content/uploads/2018/02/Strategic-Plan-Victorian-Potato-Industry-Final.pdf", sourceYear: "2015 / c.2011",
    notes: "No Gippsland-specific gross margin, cost or yield data in any public source. State averages shown for context only.",
  },
  // ---------------------------------------------------------------- Vic Mallee (no data)
  {
    regionId: "vic-mallee", segment: "unspecified", segmentLabel: "All segments",
    yieldTHa: 38.5, priceT: 251,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 5,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: null, grossMarginHa: null,
    dataQuality: "none", sourceName: "Victorian Potato Industry Strategic Plan (yield); AUSVEG Discussion Paper, ABARES 2008-09 (price)",
    sourceUrl: "https://www.auspica.org.au/wp-content/uploads/2018/02/Strategic-Plan-Victorian-Potato-Industry-Final.pdf", sourceYear: "2015 / c.2011",
    notes: "No Mallee-specific gross margin, cost or yield data in any public source. State averages shown for context only.",
  },
  // ---------------------------------------------------------------- SA Adelaide Plains
  {
    regionId: "sa-adelaide", segment: "unspecified", segmentLabel: "All segments",
    yieldTHa: 32.88, priceT: 408,
    grossIncomeHa: 13625,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 5.63,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: 12188, grossMarginHa: 1438,
    dataQuality: "state_proxy", sourceName: "Maximising returns from water: South Australia (Part 2), PIRSA/Rural Solutions SA",
    sourceUrl: "https://www.dpi.nsw.gov.au/__data/assets/pdf_file/0018/213363/Maximising-returns-from-water-in-the-Australian-vegetable-industry---South-Australia---part2.pdf", sourceYear: "c.2007 (2005 data)",
    notes: "Yield and water use are Virginia-specific; gross income ($13,625/ha), total cost and gross margin ($1,438/ha) are SA-wide aggregates, not itemised or regional. Potatoes are 22.5% of Adelaide Plains gross ag. value.",
  },
  // ---------------------------------------------------------------- SA Riverland
  {
    regionId: "sa-riverland", segment: "unspecified", segmentLabel: "All segments",
    yieldTHa: 33.38, priceT: 408,
    grossIncomeHa: 13625,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 8.63,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: 12188, grossMarginHa: 1438,
    dataQuality: "state_proxy", sourceName: "Maximising returns from water: South Australia (Part 2), PIRSA/Rural Solutions SA",
    sourceUrl: "https://www.dpi.nsw.gov.au/__data/assets/pdf_file/0018/213363/Maximising-returns-from-water-in-the-Australian-vegetable-industry---South-Australia---part2.pdf", sourceYear: "c.2007 (2005 data)",
    notes: "Yield is the Loxton/Riverland calculated figure; gross income, total cost and gross margin are the SA-wide aggregate. Riverland + Murray Mallee = 15% of national production.",
  },
  // ---------------------------------------------------------------- SA Limestone Coast
  {
    regionId: "sa-limestone", segment: "unspecified", segmentLabel: "All segments",
    yieldTHa: 39.46, priceT: 408,
    grossIncomeHa: 13625,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 4.61,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: 12188, grossMarginHa: 1438,
    dataQuality: "state_proxy", sourceName: "Maximising returns from water: South Australia (Part 2), PIRSA/Rural Solutions SA",
    sourceUrl: "https://www.dpi.nsw.gov.au/__data/assets/pdf_file/0018/213363/Maximising-returns-from-water-in-the-Australian-vegetable-industry---South-Australia---part2.pdf", sourceYear: "c.2007 (2005 data)",
    notes: "Yield is the Penola calculated figure; gross income, total cost and gross margin are the SA-wide aggregate. South East = 10% of national production; processing + seed district.",
  },
  // ---------------------------------------------------------------- NSW Riverina
  {
    regionId: "nsw-riverina", segment: "processing", segmentLabel: "Processing — French Fries",
    yieldTHa: 35, priceT: 280,
    grossIncomeHa: 9800,
    seedCostHa: 2010 + 30, fertiliserCostHa: 3300, cropProtectionCostHa: 190.77,
    irrigationCostHa: 300 + 414, waterUseMlHa: 5,
    machineryCostHa: 228.22, contractCostHa: 420,
    labourCostHa: 748, labourRateHr: 25,
    postHarvestCostHa: null, overheadPct: 0.5,
    totalVariableCostHa: 7689.98, grossMarginHa: 2110.02,
    dataQuality: "regional", sourceName: "NSW DPI Potato processing gross margin budget",
    sourceUrl: "https://archive.dpi.nsw.gov.au/__data/assets/pdf_file/0004/470029/Potato-processing-gross-margin-budget.pdf", sourceYear: "2013 (2012 prices)",
    notes: "Riverina = 70% of NSW potato production. Break-even price $219.70/t, break-even yield 27.5 t/ha.",
  },
  {
    regionId: "nsw-riverina", segment: "fresh", segmentLabel: "Fresh — Summer Crop",
    yieldTHa: 34, priceT: null,
    grossIncomeHa: 15300,
    seedCostHa: 2010, fertiliserCostHa: 3300, cropProtectionCostHa: 210,
    irrigationCostHa: 300 + 440.25, waterUseMlHa: 5,
    machineryCostHa: 221.32, contractCostHa: null,
    labourCostHa: 2091.5, labourRateHr: 25,
    postHarvestCostHa: 570 + 3630, overheadPct: 0.5 + 15,
    totalVariableCostHa: 15144.55, grossMarginHa: 155.45,
    dataQuality: "regional", sourceName: "NSW DPI Potato fresh summer gross margin budget",
    sourceUrl: "https://archive.dpi.nsw.gov.au/__data/assets/pdf_file/0003/470028/Potato-fresh-summer-gross-margin-budget.pdf", sourceYear: "2013 (2012 prices)",
    notes: "Source prices per bag, not per tonne (500 bags/ha @ $26 + 100 bags/ha @ $23 = 600 bags/ha at $25.50 average bag price) — priceT left blank rather than guessing a bag-to-tonne conversion. Gross income ($15,300/ha), totals and gross margin are as published. Overhead = 0.5% levy + 15% agent's commission. Varieties: Coliban, Desiree.",
  },
  {
    regionId: "nsw-riverina", segment: "fresh_winter", segmentLabel: "Fresh — Winter Crop",
    yieldTHa: 25, priceT: null,
    grossIncomeHa: 14000,
    seedCostHa: 1120, fertiliserCostHa: 3300, cropProtectionCostHa: 374.38,
    irrigationCostHa: 240 + 457.05, waterUseMlHa: 4,
    machineryCostHa: 179.92, contractCostHa: null,
    labourCostHa: 1763.5, labourRateHr: 25,
    postHarvestCostHa: 475 + 3025, overheadPct: 0.5 + 15,
    totalVariableCostHa: 13104.84, grossMarginHa: 895.16,
    dataQuality: "regional", sourceName: "NSW DPI Potato fresh winter gross margin budget",
    sourceUrl: "https://archive.dpi.nsw.gov.au/__data/assets/pdf_file/0003/470037/Potato-fresh-winter-gross-margin-budget.pdf", sourceYear: "2013 (2012 prices)",
    notes: "Source prices per bag, not per tonne (500 bags/ha @ $28) — priceT left blank rather than guessing a bag-to-tonne conversion. Gross income ($14,000/ha) is the published figure. Paddock yield range 20-30 t/ha. Seed cost is own-seed carried from summer crop. Overhead = 0.5% levy + 15% agent's commission.",
  },
  // ---------------------------------------------------------------- NSW Tablelands (no data)
  {
    regionId: "nsw-tablelands", segment: "unspecified", segmentLabel: "All segments",
    yieldTHa: null, priceT: 403,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: null,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: null, grossMarginHa: null,
    dataQuality: "none", sourceName: "NSW DPI Potato processing gross margin budget (context only); AUSVEG Discussion Paper, ABARES 2008-09 (state price)",
    sourceUrl: "https://archive.dpi.nsw.gov.au/__data/assets/pdf_file/0004/470029/Potato-processing-gross-margin-budget.pdf", sourceYear: "2013",
    notes: "No Tablelands budget was ever published (20% of NSW production). NSW DPI states Tablelands yields run ~20% above Riverina — apply that adjustment to the Riverina fresh-summer budget as an approximation only, not an observed figure. The entire Tablelands summer crop is sold fresh.",
  },
  // ---------------------------------------------------------------- WA Manjimup
  {
    regionId: "wa-manjimup", segment: "ware", segmentLabel: "Ware / Table",
    yieldTHa: 42.8, priceT: 363.79,
    grossIncomeHa: 15570,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 5.86,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: 8964, grossMarginHa: 6606,
    dataQuality: "state_proxy", sourceName: "Maximising returns from water: Western Australia, DAFWA/NSW DPI (Table 12, Gartrell 1999)",
    sourceUrl: "https://www.dpi.nsw.gov.au/__data/assets/pdf_file/0003/201099/Maximising-returns-from-water-in-the-Australian-vegetable-industry---Western-Australia.pdf", sourceYear: "2005",
    notes: "Water use (5.86 ML/ha, 7.2 t/ML WUE) is Manjimup-specific and directly measured. Yield and gross margin are WA state-level, applied to all WA districts by the source study. Gross income ($15,570/ha) is the sum of the published cost ($8,964/ha) and margin ($6,606/ha) figures. An alternative 2013 PT13009 model gives $7,900/ha gross margin at seed price $550/t.",
  },
  // ---------------------------------------------------------------- WA Perth
  {
    regionId: "wa-perth", segment: "ware", segmentLabel: "Ware / Table",
    yieldTHa: 41, priceT: null,
    grossIncomeHa: 19400,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 2.65,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: 11500, grossMarginHa: 7900,
    dataQuality: "state_proxy", sourceName: "PT13009 Final Report, McPharlin et al., DAFWA/HAL",
    sourceUrl: "https://ausveg.com.au/app/data/technical-insights/docs/PT13009.PDF", sourceYear: "2013",
    notes: "Modelled Medina/Dandaragan gross margin ($7,900/ha, costs less freight $11,500/ha, gross income $19,400/ha). Water use (2.65 ML/ha Perth district, 15.7 t/ML WUE) is directly measured. Multi-grade PMC pricing (Class 1 $970/t, Class 2 $420/t, Smalls $705/t) means revenue can't be derived from a single price x yield — priceT left blank rather than guessing a blended rate.",
  },
  // ---------------------------------------------------------------- Qld Atherton
  {
    regionId: "qld-atherton", segment: "fresh", segmentLabel: "Fresh (Sebago)",
    yieldTHa: 30, priceT: null,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 3,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: null, grossMarginHa: 2003.56,
    dataQuality: "regional", sourceName: "Potato Information Kit — Annual Update 1998, Queensland DPI",
    sourceUrl: "http://era.dpi.qld.gov.au/id/eprint/1658/9/8pot_up.pdf", sourceYear: "1998",
    notes: "28 years old — treat as indicating cost structure, not current magnitude. Source prices at $15/bag on a 30 t/ha crop, not per tonne — priceT left blank rather than guessing a bag weight. No itemised seed/fertiliser/crop protection/machinery/labour costs published.",
  },
  // ---------------------------------------------------------------- Qld Lockyer
  {
    regionId: "qld-lockyer", segment: "fresh", segmentLabel: "Fresh (Brushed Sebago)",
    yieldTHa: 25, priceT: null,
    grossIncomeHa: null,
    seedCostHa: null, fertiliserCostHa: null, cropProtectionCostHa: null,
    irrigationCostHa: null, waterUseMlHa: 3,
    machineryCostHa: null, contractCostHa: null,
    labourCostHa: null, labourRateHr: null,
    postHarvestCostHa: null, overheadPct: null,
    totalVariableCostHa: null, grossMarginHa: 2432.77,
    dataQuality: "regional", sourceName: "Potato Information Kit — Annual Update 1998, Queensland DPI",
    sourceUrl: "http://era.dpi.qld.gov.au/id/eprint/1658/9/8pot_up.pdf", sourceYear: "1998",
    notes: "28 years old — treat as indicating cost structure, not current magnitude. Break-even yield 14 t/ha, break-even price $197.69/t. Break-even price implies a blended/graded market price, not a single $360/t rate; with no itemised cost breakdown published, priceT and gross income are left blank rather than reverse-engineered — only the net gross margin ($2,432.77/ha) is a directly published figure.",
  },
];

// National reference constants shown alongside every region for context.
export const NATIONAL_CONTEXT = {
  labourAdultFullTime: { value: 25.74, unit: "$/hr", sourceName: "Horticulture Award pay & piece rates, Fair Work Ombudsman", sourceUrl: "https://horticulture.fairwork.gov.au/pay-and-piece-rates", sourceYear: "2026" },
  labourAdultCasual: { value: 32.18, unit: "$/hr", sourceName: "Horticulture Award pay & piece rates, Fair Work Ombudsman", sourceUrl: "https://horticulture.fairwork.gov.au/pay-and-piece-rates", sourceYear: "2026" },
  rdLevy: { value: 0.48, unit: "$/t", sourceName: "AUSVEG Potatoes Australia Autumn 2023", sourceUrl: "https://ausveg.com.au/app/uploads/2023/04/AUSVEG_Potatoes_Autumn_2023_combined-lr.pdf", sourceYear: "2023" },
  costInflation20192023: { value: 110.3, unit: "% cost rise 2019-2023 vs 4.34% price rise", sourceName: "Mok & Johns 2025, Australasian Agribusiness Perspectives Vol 28 Paper 6", sourceUrl: "https://bpb-ap-se2.wpmucdn.com/blog.une.edu.au/dist/d/1339/files/2025/06/AAP-Vol-28-Paper-6-Mok-and-Johns.pdf", sourceYear: "2025" },
};
